---

- name: Register if Docker exists on the system
  stat:
    path: /usr/bin/docker
  register: docker_bin

- name: Run Docker install script
  script: docker_install_script/get-docker.sh
  changed_when: False
  when: docker_bin.stat.exists == False and ansible_distribution == 'Ubuntu'

- name: Install epel-release
  package:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'
  changed_when: False

- name: Install Docker and Docker-Compose on Fedora
  package:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_distribution == 'Fedora'
  notify: start docker

- name: Install Docker on CentOS 7
  package:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_version < '8'
  notify: start docker

- name: Install Docker-CE repository on CentOS 8
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '8'
