---
# - name: Tear down existing services
#   docker_compose:
#     project_src: /opt/b404/b404/docker-compose.yml
#     state: absent

# - name: Run `docker-compose up`
#   docker_compose:
#     project_src: /opt/b404/b404/docker-compose.yml
#     build: no