---
- name: Install epel-release
  package:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'
  changed_when: False

- name: Install Docker and Docker-Compose on Fedora
  package:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_distribution == 'Fedora'
  notify: start docker

- name: Install Docker on CentOS 7
  package:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_version < '8'
  notify: start docker

- name: Install Docker-CE repository on CentOS 8
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '8'

# - name: Install Docker-CE on CentOS 8
#   package:
#     name: docker-ce
#   when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '8'
#   notify: start docker

- name: Install Docker-Compose on CentOS 8
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.3/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '8'

- name: Make Docker-Compose runnable
  file:
    path: /usr/bin/docker-compose
    mode: 0755
    owner: root
    group: root
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '8'

- name: Install python pip on CentOS 7
  package:
    name: python-pip
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_version < '8'

- name: Install python pip on CentOS 8
  package:
    name: python3-pip
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '8'

- name: Pip install docker libs
  pip:
    name:
      - docker
      - requests