version: "3"

services:

  rp:
    image: nginx:latest
    restart: always
    volumes:
      - /opt/b404/nginx:/etc/nginx/
      - /opt/b404/nginx-default:/var/www/nginx-default
    ports:
      - 443:443
      - 80:80
    links:
      - "be-master"
      - "be-testing"
      - "be-dev"
      - "be-debug"
      - "fe-master"
      - "fe-testing"
      - "fe-dev"
      - "adminer"
      - "logger"

  fe-master:
    image: znl2181/b404.fe:master
    restart: always
    environment:
      - API_URL=http://master.blink-404.com

  fe-testing:
    image: znl2181/b404.fe:testing
    restart: always
    environment:
      - API_URL=http://testing.blink-404.com

  fe-dev:
    image: znl2181/b404.fe:dev
    restart: always
    environment:
      - API_URL=http://dev.blink-404.com

  be-master:
    image: znl2181/b404.be:master
    restart: always
    environment:
      - DB_NAME=db-master
    links:
      - "db-master"

  be-testing:
    image: znl2181/b404.be:testing
    restart: always
    environment:
      - DB_NAME=db-testing
    links:
      - "db-testing"
    restart: always

  be-dev:
    image: znl2181/b404.be:dev
    restart: always
    environment:
      - DB_NAME=db-dev
    links:
      - "db-dev"

  be-debug:
    image: znl2181/b404.be:debug
    restart: always
    environment:
      - DB_NAME=db-dev
    links:
      - "db-dev"

  db-master:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: b404
      MYSQL_DATABASE: venture_creations
      MYSQL_USER: b404
      MYSQL_PASSWORD: b404
    volumes:
      - /opt/b404/db/master:/var/lib/mysql

  db-testing:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: b404
      MYSQL_DATABASE: venture_creations
      MYSQL_USER: b404
      MYSQL_PASSWORD: b404
    volumes:
      - /opt/b404/db/testing:/var/lib/mysql

  db-dev:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: b404
      MYSQL_DATABASE: venture_creations
      MYSQL_USER: b404
      MYSQL_PASSWORD: b404
    volumes:
      - /opt/b404/db/dev:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    links:
      - "db-master"
      - "db-testing"
      - "db-dev"

  wt:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup

  logger:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_TAILSIZE=3000
      - DOZZLE_BASE=/logger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
