version: "3"

services:

  rp:
    image: nginx:latest
    volumes:
      - /opt/b404/nginx:/etc/nginx/
      - /opt/b404/nginx-default:/var/www/nginx-default
    ports:
      - 443:443
      - 80:80
    links:
      - "be"
      - "adminer"
    restart: always

  be:
    image: znl2181/b404.be:latest
    # ports:
    #   - 8080:8080
    #   - 9990:9990
    restart: always
    links:
      - "db"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: b404
      MYSQL_DATABASE: b404
      MYSQL_USER: b404
      MYSQL_PASSWORD: b404
    # ports:
    #   - 3306:3306
    volumes:
      - /opt/b404/db:/var/lib/mysql

  adminer:
    image: adminer
    # ports:
    #   - 4040:8080
    links:
      - "db"
