---
- name: Install firewalld
  package:
    name: firewalld
    state: present
  notify:
      - start firewalld

- name: Open ssh port
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
    zone: public
  notify:
    - reload firewalld