---

- name: Install firewalld
  package:
    name: firewalld
    state: present
  notify:
      - start firewalld

- name: Open ssh port
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
    zone: public
  notify:
    - reload firewalld

- name: Open cockpit port for Centos8 and Fedora
  firewalld:
    service: cockpit
    permanent: yes
    state: enabled
    zone: public
  notify:
    - reload firewalld
  when:
    - ansible_distribution == 'CentOS' and ansible_distribution_version >= '8'
    - ansible_distribution == 'Fedora' and ansible_distribution_version >= '30'

- name: Open cockpit port for CentOS7
  firewalld:
    port: 9090/tcp
    permanent: yes
    state: enabled
    zone: public
  notify:
    - reload firewalld
  when: ansible_distribution == 'CentOS' and ansible_distribution_version < '8'
