---
- name: Add user `bubba`
  user:
    name: bubba
    shell: /bin/zsh
    groups: wheel,b404

- name: Check if zshrc exists
  stat:
    path: /home/bubba/.zshrc
  register: stat_result

- name: Download grml-zsh
  get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: /home/bubba/.zshrc
    mode: 600
    owner: bubba
  when: not stat_result.stat.exists

- name: Fix terminal issue
  lineinfile:
    path: /home/bubba/.zshrc
    regexp: '^export\sTERM=xterm'
    line: 'export TERM=xterm'

- name: Add user `blink-404`
  user:
    name: blink-404
    shell: /bin/bash
    groups: b404
