---

- name: Create new user
  user:
    name: "{{ user }}"
    create_home: yes
    system: yes
    password: "{{ user_pass }}"
    group: sudo
    shell: /bin/bash

- name: Set up authorized keys
  authorized_key:
    user: "{{ user }}"
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/srdev_rsa.pub