version: "3"

services:

  reverse_proxy:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - /opt/b404/nginx:/etc/nginx/
    ports:
      - 443:443
    restart: always
    networks:
      - backend

  b404.be:
    image: znl2181/b404.be:master
    container_name: b404.be
    ports:
      - 8080:8080
      - 9990:9990
    restart: always
    networks:
      - backend
    depends_on:
      - reverse_proxy

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: b404
      MYSQL_DATABASE: b404
      MYSQL_USER: b404
      MYSQL_PASSWORD: b404
    volumes:
      - /opt/b404/db:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 4040:8080

networks:
  backend:
